### ISSUE TITLE
Error opening font (mpv --no-ass)

### ISSUE THREAD

**Issue by kax4** [pigoz/libass-ct#5]
Subs play fine but mpv complain:
<pre><span>[osd/libass] Glyph 0x49 not found, selecting one more font for (Trebuchet MS, 400, 0)
[osd/libass] Error opening font: '/Library/Fonts/Trebuchet MS.ttf', 1
[osd/libass] Glyph 0x20 not found, selecting one more font for (Trebuchet MS, 400, 0)
[osd/libass] Error opening font: '/Library/Fonts/Trebuchet MS.ttf', 1
[osd/libass] Glyph 0x6B not found, selecting one more font for (Trebuchet MS, 400, 0)
[osd/libass] Error opening font: '/Library/Fonts/Trebuchet MS.ttf', 1
[osd/libass] Glyph 0x6E not found, selecting one more font for (Trebuchet MS, 400, 0)
[osd/libass] Error opening font: '/Library/Fonts/Trebuchet MS.ttf', 1
[osd/libass] Glyph 0x6F not found, selecting one more font for (Trebuchet MS, 400, 0)
[osd/libass] Error opening font: '/Library/Fonts/Trebuchet MS.ttf', 1
[osd/libass] Glyph 0x77 not found, selecting one more font for (Trebuchet MS, 400, 0)</span></pre>

**Comment by pigoz** [comment]
Check again with official libass (they now merged the coretext code and added some improvements to the platform independent code).
