### ISSUE TITLE
Style override codes in ASS files are not recognized

### ISSUE THREAD

**Issue by hkenneth** [pigoz/libass-ct#6]
In the following ASS codes, {\fnMyriad Pro\fs47} is not recognized. Only the font defined in style statement is used in the sub:

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Hiragino Sans GB W6,60,&H00FFFFFF,&H0000FFFF,&H17000000,&HAC000000,0,0,0,0,100,100,0,0,0,2,3,2,20,20,66,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:02:57.27,0:02:59.06,Default,NTP,0000,0000,0000,,我们可以去车上待着...\N{\fnMyriad Pro\fs47}We could jump in the car if...

**Comment by pigoz** [comment]
Seems fixed in official libass, closing.
